### ISSUE TITLE
Changing the filters

### ISSUE THREAD

**Issue by owodo** [snigui/materials#4]
I played the filters. When I wanted to change the filter, I got the error in the second panel (top):

![image](https://user-images.githubusercontent.com/52643989/95897338-5c7fda80-0d5b-11eb-848f-e5c39fa01a84.png)

**Comment by snigui** [comment]
I will try to reproduce this let you know, thank you!

**Comment by snigui** [comment]
Hi Olga, 

So I reproduced it and it works for me. Usually for errors, refreshing the page should help. And an error on line 85 is the vizier db call and deals with the demo vizier server rather than the app code.
![image](https://user-images.githubusercontent.com/40993241/95902821-54c43400-0d63-11eb-94d2-567099a0a5a0.png)

**Comment by owodo** [comment]
I tried, it worked nicely this time.
